name: adorafrika
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  cached_network_image: ^3.2.2
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  another_flushbar: ^1.10.29
  cherry_toast: ^1.0.6
  data_connection_checker_tv: ^0.3.5-nullsafety
  flutter_switch: ^0.3.2
  awesome_bottom_navigation: ^0.0.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  dropdown_formfield: ^0.1.4
  dropdown_textfield: ^1.0.4
  flutter_svg: ^1.1.5
  flutter_rating_bar: ^4.0.1
  lottie: ^1.4.1
  getwidget: ^3.0.1
  font_awesome_flutter: ^10.1.0
  extended_tabs: ^3.0.3
  audioplayers: ^1.1.1
  sliding_up_panel: ^2.0.0+1 
  intl: ^0.17.0
  #cloud_firestore: ^3.5.1
  google_fonts: ^3.0.1
  flutter_lorem: ^2.0.0
  sliding_up_panel2: ^3.2.2
  encrypt: ^5.0.1
  flutter_easyloading: ^3.0.5
  dio: ^4.0.6
  permission_handler: any
  record: ^3.0.3
  simple_ripple_animation: ^0.0.3
  provider: ^6.0.3
  path_provider: any
  percent_indicator: ^4.2.2
  fluttertoast: ^8.0.9
  flutter_speed_dial: ^6.2.0
  video_player: ^2.4.7
  image_picker: ^0.8.6
  dropdown_search: ^5.0.3
  fl_country_code_picker: ^0.0.4
  profile: ^0.0.1
  file_picker: ^5.2.2
  audio_waveforms: ^0.1.5+1
  flutter_staggered_grid_view: ^0.4.0
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_displaymode: ^0.4.1
  device_info_plus: ^8.0.0
  audio_service: ^0.18.7
  receive_sharing_intent: ^1.4.5
  flip_card: ^0.6.0
  audiotagger: ^2.2.1
  share_plus: ^6.3.0
  on_audio_query: ^2.6.1
  material_design_icons_flutter: ^6.0.7096
  marquee: ^2.2.3
  youtube_explode_dart: ^1.12.3
  palette_generator: ^0.3.3+2
  html_unescape: ^2.0.0
  supabase: ^1.2.0
  dart_des: ^1.0.2
  change_app_package_name: ^1.1.0
  package_info_plus: ^3.0.2
  salomon_bottom_bar: ^3.3.1
  flutter_archive: ^5.0.0
  country_state_city_picker: ^1.2.8
  csc_picker: ^0.2.6
  chewie: ^1.3.6
  flutter_native_splash: ^2.2.16
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.6.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-AdorAfrika.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-AdorAfrika.png"

flutter_native_splash:
  color: "#000001"
  image: assets/images/logo-AdorAfrika.png  
  android: true
  web: true
  ios: true
  android_12:
    image: assets/images/logo-AdorAfrika.png
    color: "#000000"
    icon_background_color: "#FFFFFF"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/music/
    - assets/images/auth/
    - assets/images/playlist/
    - assets/images/panigeriques/
    - assets/images/fashion/
    - assets/lottiefiles/



msix_config:
  display_name: adorAfrika
  publisher_display_name: AZANMASSOU Valdo
  identity_name: com.stanleylab.adorafrika
  icons_background_color: transparent
  logo_path: assets/images/logo-AdorAfrika.png
  file_extension: .mp3, .m4a, .mp4, .aac
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
